id: IC4955951
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T22:47:33+00:00'
last_modified: '2022-06-15T17:50:22.035886+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23711
  title: ལྷ་མོ་རིག་བྱེད་མ་ལ་བསྟོད་པའི་རྒྱ་ཆེར་འགྲེལ་པ་རྡོ་རྗེ་གསུམ་གྱི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8CC6:
      image_group_id: I1KG23811
      title: Volume 1 of lha mo rig byed ma la bstod pa'i rgya cher 'grel pa rdo rje
        gsum gyi snang ba/
      total_pages: 264
      order: 1
      base_file: 8CC6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
